#                                           
#     .vir.                                d$b
#  .d$$$$$$b.    .cd$$b.     .d$$b.   d$$$$$$$$$$$b  .d$$b.      .d$$b.
#  $$$$( )$$$b d$$$()$$$.   d$$$$$$$b Q$$$$$$$P$$$P.$$$$$$$b.  .$$$$$$$b.
#  Q$$$$$$$$$$B$$$$$$$$P"  d$$$PQ$$$$b.   $$$$.   .$$$P' `$$$ .$$$P' `$$$
#    "$$$$$$$P Q$$$$$$$b  d$$$P   Q$$$$b  $$$$b   $$$$b..d$$$ $$$$b..d$$$
#   d$$$$$$P"   "$$$$$$$$ Q$$$     Q$$$$  $$$$$   `Q$$$$$$$P  `Q$$$$$$$P
#  $$$$$$$P       `"""""   ""        ""   Q$$$P     "Q$$$P"     "Q$$$P"
#  `Q$$P"                                  """
#

# ===== Compilation flags =====
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
RUSTFLAGS="-C target-cpu=native"

# ===== Portage setup =====
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
FEATURES="parallel-fetch parallel-install binpkg-logs sandbox" 
EMERGE_DEFAULT_OPTS="--ask --with-bdeps=y --getbinpkg --binpkg-respect-use=y"
GENTOO_MIRRORS="https://mirror.yandex.ru/gentoo-distfiles/ \
https://gentoo-mirror.alexxy.name/ \
https://ru.mirrors.cicku.me/gentoo/"
PORTAGE_BINHOST="https://mirror.yandex.ru/gentoo-distfiles/releases/amd64/binpackages/23.0/x86-64/ \
https://gentoo-mirror.alexxy.name/releases/amd64/binpackages/23.0/x86-64/ \
https://ru.mirrors.cicku.me/gentoo/releases/amd64/binpackages/23.0/x86-64/"

# ===== USE =====
USE="dbus dracut grub png jpeg pdf webp json policykit amd64 unicode vulkan wifi opengl alsa cli crypt iconv ssl dist-kernel -geolocation -gps"

# ===== Drivers and Devices =====
VIDEO_CARDS="amdgpu"  
INPUT_DEVICES="libinput"  

# ===== GRUB (BIOS) =====
GRUB_PLATFORMS="pc"  
GRUB_TARGET="i386-pc"
#GRUB_PLATFORMS="efi-64"
#GRUB_TARGET="x86_64-efi"
# for the BIOS version of the grub in `cfdisk` utility select DOS partition label.
# Layout:
# /dev/sda1 swap
# /dev/sda2 /
# for the UEFI version of the grub in `cfdisk` utility select GPT partition label.
# Layout:
# /dev/sda1 /boot/efi
# /dev/sda2 swap
# /dev/sda3 /
# also add '--efi-directory=/boot/efi' to the `grub-install` command
