#                                           
#     .vir.                                d$b
#  .d$$$$$$b.    .cd$$b.     .d$$b.   d$$$$$$$$$$$b  .d$$b.      .d$$b.
#  $$$$( )$$$b d$$$()$$$.   d$$$$$$$b Q$$$$$$$P$$$P.$$$$$$$b.  .$$$$$$$b.
#  Q$$$$$$$$$$B$$$$$$$$P"  d$$$PQ$$$$b.   $$$$.   .$$$P' `$$$ .$$$P' `$$$
#    "$$$$$$$P Q$$$$$$$b  d$$$P   Q$$$$b  $$$$b   $$$$b..d$$$ $$$$b..d$$$
#   d$$$$$$P"   "$$$$$$$$ Q$$$     Q$$$$  $$$$$   `Q$$$$$$$P  `Q$$$$$$$P
#  $$$$$$$P       `"""""   ""        ""   Q$$$P     "Q$$$P"     "Q$$$P"
#  `Q$$P"                                  """
#

# after installing do command delete previous make.conf and: cd Gentoo-makeconf, mv make.conf /etc/portage, cd .. ,rm -rf Gentoo-makeconf 
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

# ===== Portage setup =====
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="*"
MAKEOPTS="-j4 -l5"
FEATURES="parallel-fetch parallel-install binpkg-logs sandbox" 
EMERGE_DEFAULT_OPTS="--ask --with-bdeps=y --getbinpkg --binpkg-respect-use=y"
RUSTFLAGS="-C target-cpu=native"
GENTOO_MIRRORS="https://mirror.yandex.ru/gentoo-distfiles/distfiles/ \
https://gentoo-mirror.alexxy.name/distfiles/"
PORTAGE_BINHOST="https://mirror.yandex.ru/gentoo-distfiles/releases/amd64/binpackages/23.0/x86-64/ \
https://gentoo-mirror.alexxy.name/releases/amd64/binpackages/23.0/x86-64/"
LINGUAS="en"

# ===== USE =====
USE="-gnome -kde dbus png jpeg pdf webp json policykit amd64 unicode vulkan wifi opengl alsa cli crypt iconv ssl udev xorg X curl -geolocation -gps"

# ===== Drivers and Devices =====
VIDEO_CARDS="amdgpu"  
INPUT_DEVICES="libinput"  

# ===== GRUB (BIOS) =====
GRUB_PLATFORMS="pc"  
GRUB_TARGET="i386-pc"
#GRUB_PLATFORMS="efi-64"
#GRUB_TARGET="x86_64-efi"
# and run this to install grub on EFI system: grub-install --efi-directory=/efi
